// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtflqcielznzdqdrkydr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZmxxY2llbHpuemRxZHJreWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzMyMDYsImV4cCI6MjA2NTMwOTIwNn0.KPnlh8nz5clDc0fgsEIm-ZE4Wu3XWvz1utRDolZiinQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);